module.exports = {
  bookmark: require('./bookmark'),
  calendar: require('./calendar'),
  check: require('./check'),
  chevronDown: require('./chevron-down'),
  chevronLeft: require('./chevron-left'),
  chevronRight: require('./chevron-right'),
  chevronUp: require('./chevron-up'),
  clock: require('./clock'),
  close: require('./close'),
  cog: require('./cog'),
  external: require('./external'),
  musicNote: require('./music-note'),
  pause: require('./pause'),
  pin: require('./pin'),
  play: require('./play'),
  refresh: require('./refresh'),
  share: require('./share'),
  shoppingCart: require('./shopping-cart'),
  star: require('./star'),
  warning: require('./warning')
};